### ISSUE TITLE
Throttle deadzone

### ISSUE THREAD

**Issue by stefan-girlich** [Kethen/RemasteredControls_GTpsp#3]
I noticed that the in-game throttle (and probably also the brake) input only starts around 16% analog trigger input (checked via [Gamepad Tester](https://hardwaretester.com/gamepad)), making gentle throttle application more difficult.

Do you think this is possible to fix, similar to the existing deadzone fix for the steering?

### Setup
- PPSSPP v1.16.6
- Gran Turismo UCES01245 2.00
- Razor Kishi v2

**Comment by Kethen** [comment]
"0.16", the plugin has a ~0.04 inner deadzone and ~0.08 outer deadzone to filter out stick normalization/deadzone weirdness on ppsspp itself, **_with the default deadzone radius of 0.1 in ppsspp_**, it adds up to roughly 0.14 on the inner side with a bit of float to int loss + ppsspp normalization; Reducing that to 0.0 in ppsspp settings would then give you a roughly 0.04 start value

[I guess I could consider further lowering that to 0.02 and still have ppsspp weirdness filtered out](https://github.com/Kethen/RemasteredControls_GTpsp/actions/runs/7003362418), but at that point it likely won't make too big of a difference

Also, how much trigger travel does the kishi even have..? It might as well has too little for good muscle memory, perhaps try another controller with more sensitive trigger start and longer trigger travel, hell, my steam deck's triggers start at physically 0.2~0.3, but at least those are long traveling triggers and my brain could get used to them

---

Since you brought up the steering fix, here's a bit of an explainer

The steering deadzone fix bypasses the "psp input layer" and insert input directly to the "ps3 input layer" in order to remove most of the psp analog stick deadzone; the same goes for throttle and brake input, inserting input to the ps3 leftovers and flag them as analog input instead of digital

Meanwhile, the game's built in analog response curve is not perfect, throttle/brake/steering starts at a low value but not 0 , and funny enough, the ps3 input layer's response curve also flatted out ~0.1-0.77 throttle input making a curve looking like `__/`, and not on brake

I made some attempt to go deeper at some point as to insert analog input behind the "ps3 analog layer", but that just breaks replay/ghost, which indicates that the replay/ghost system stores user input frames on the "ps3 input layer", instead of vehicle position, and leverages reproducible physics

Given that, any attempt to further mess with the ps3 analog response curve would just result in incompatibility with past replays and ghosts, unless something new can be found from further reverse engineering, which is likely beyond my freetime/skill level

---

If disabling ppsspp analog stick deadzone still isn't good enough for you, look at the hooking done on commit https://github.com/Kethen/RemasteredControls_GTpsp/blob/ce86001629af13cb5ded89844d86a788b1a9f486/main.c and probably build your own version that has better input response but broken ghost/replay

**Comment by Kethen** [comment]
I think I accidentally removed something I wanted to type in the previous comment

@stefan-girlich You should be able to remove 0.1 of the observed deadzone by changing the default analog deadzone radius from 0.1 to 0.0 in ppsspp settings, leaving at most 0.04, or 0.02 in the new build on github action
